name: Java CI with Maven

on:
  push:
    branches: [ "ArhanErdogan_SelectionTool" ]
  pull_request:
    branches: [ "ArhanErdogan_SelectionTool" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build and run tests with Maven
        run: mvn -B verify --file pom.xml -s .maven-settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
